export const RANDOM_PLAYER_POSITION = 'RANDOM_PLAYER_POSITION'
export const PLAYER_MOVEMENT = 'PLAYER_MOVEMENT'
export const HEALTH_COLLISION = 'HEALTH_COLLISION'
export const ENEMY_COLLISION = 'ENEMY_COLLISION'
export const WEAPON_COLLISION = 'WEAPON_COLLISION'
export const GATE_COLLISION = 'GATE_COLLISION'
export const BOSS_COLLISION = 'BOSS_COLLISION'
export const TOGGLE_LIGHT = 'TOGGLE_LIGHT'



